#!/bin/bash
#
# July 2021 - Gene Weber
# Did the following to get the Arrow Tests to pass.
#
# Build with -DARROW_BUILD_TESTS=ON
# Reference -> https://arrow.apache.org/docs/developers/cpp/building.html
#
# Generate parquet submodule in the repository and set the PARQUET_TEST_DATA env variable.
# Reference -> https://arrow.apache.org/docs/developers/cpp/development.html
#
# Set the ARROW_TEST_DATA environmental variable.
# Reference -> None. Failure message indicated fix.
#
# Run ctest.
# Reference -> https://arrow.apache.org/docs/developers/cpp/development.html
# Reference -> https://wesm.github.io/arrow-site-test/developers/cpp.html
#
# Build setup used for unit testing is listed at the bottom of this file.

export ARROW_ROOT="${ARROW_ROOT:-/home/centos/arrow}"
export ARROW_BUILD="${ARROW_BUILD:-$ARROW_ROOT/cpp/build}"
export PARQUET_TEST_DATA="${PARQUET_TEST_DATA:-$ARROW_ROOT/cpp/submodules/parquet-testing/data}"
export ARROW_TEST_DATA="${ARROW_TEST_DATA:-$ARROW_ROOT/testing/data}"

cd $ARROW_ROOT
git submodule update --init

NPROC=$(nproc)  # number of processing units available

cd $ARROW_BUILD
sudo PARQUET_TEST_DATA=$PARQUET_TEST_DATA ARROW_TEST_DATA=$ARROW_TEST_DATA /usr/local/bin/ctest -j $NPROC -L unittest -O $ARROW_ROOT/cpp/ctest.log 


# Build setup that was used for debug/testing (all 71 tests passed):
#
# : ${ARROW_DEPENDENCY_SOURCE:=BUNDLED}
# 
# mkdir $ARROW_BUILD
# cd $ARROW_BUILD
# 
# cmake $ARROW_ROOT/cpp -G Ninja \
#     -DCMAKE_BUILD_TYPE=Debug \
#     -DARROW_EXTRA_ERROR_CONTEXT=ON \
#     -DARROW_BUILD_SHARED=ON \
#     -DARROW_BUILD_STATIC=OFF \
#     -DARROW_COMPUTE=ON \
#     -DARROW_CSV=ON \
#     -DARROW_CUDA=OFF \
#     -DARROW_DATASET=ON \
#     -DARROW_DEPENDENCY_SOURCE=${ARROW_DEPENDENCY_SOURCE} \
#     -DARROW_DEPENDENCY_USE_SHARED=ON \
#     -DARROW_FILESYSTEM=ON \
#     -DARROW_FLIGHT=OFF \
#     -DARROW_GANDIVA=ON \
#     -DARROW_GANDIVA_JAVA=OFF \
#     -DARROW_HDFS=OFF \
#     -DARROW_HIVESERVER2=OFF \
#     -DARROW_IPC=ON \
#     -DARROW_JEMALLOC=OFF \
#     -DARROW_MIMALLOC=OFF \
#     -DARROW_JSON=OFF \
#     -DARROW_ORC=OFF \
#     -DARROW_PARQUET=ON \
#     -DARROW_PLASMA=ON \
#     -DARROW_PLASMA_JAVA_CLIENT=OFF \
#     -DARROW_PYTHON=OFF \
#     -DARROW_S3=OFF \
#     -DARROW_WITH_BROTLI=ON \
#     -DARROW_WITH_BZ2=ON \
#     -DARROW_WITH_LZ4=ON \
#     -DARROW_WITH_SNAPPY=ON \
#     -DARROW_WITH_ZLIB=ON \
#     -DARROW_WITH_ZSTD=ON \
#     -DORC_SOURCE=BUNDLED \
#     -DARROW_BUILD_BENCHMARKS=OFF \
#     -DARROW_BUILD_EXAMPLES=OFF \
#     -DARROW_BUILD_INTEGRATION=OFF \
#     -DARROW_BUILD_UTILITIES=OFF \
#     -DARROW_BUILD_TESTS=ON \
#     -DARROW_ENABLE_TIMING_TESTS=OFF \
#     -DARROW_FUZZING=OFF \
#     -DARROW_USE_ASAN=OFF \
#     -DARROW_USE_TSAN=OFF \
#     -DARROW_USE_UBSAN=OFF \
#     $ARROW_CMAKE_OPTIONS
# 
# ninja -j $NPROC
# ninja install
