#!/bin/bash
#
# August 2021 -Gene Weber
#
# Upgrade bison to version 3.7.6
# https://github.com/westes/flex/releases/tag/v2.6.4

# Get release
wget https://ftp.gnu.org/gnu/bison/bison-3.7.6.tar.gz
tar -xvf bison-3.7.6.tar.g

# Build & install bison
./configure  2>&1 | tee config.log
make  2>&1 | tee make.log
sudo make install 2>&1 | tee inst.log
make installcheck 2>&1 | tee inst_chk.log

# Clear the bash hash so it uses the new version
hash -d bison

