#! /bin/bash
# June 2022 - Gene Weber
# Convert VERBOSE make log into compile script.

if [ "$#" -ne 4 ]; then
    echo "make_comp_script  input_file  output_file  new_C++_file_name  cling_installation_ directory"
    exit 1
fi

NAME_ROOT=`awk -F'.' '{print $1}' <<< $3`

grep "c++" $1 | \
sed s/\ $// | \
sed s/^cd\ .*c++\ /\#\\ng++\ / | \
sed s/^.*c++\ /\#\#\\ng++\ / | \
sed s/\ \ */\ \\n/g | \
sed '/^-o/N;s/\n//' | \
sed '/^-c/N;s/\n//' | \
sed '/^-lm/N;s/\n//' | \
sed s/CMakeFiles.*cling\.cpp/$3/ | \
sed s/^-c\ .*cling\.cpp/-c\ $3/ | \
sed s/^-o\ .*cling/-o\ $NAME_ROOT/ | \
sed "s|^\.\./\.\./\.\./\.\.|\$INSTALL_DIR/obj|" | \
sed "s|^\.\./\.\.|\$INSTALL_DIR/obj/tools/cling|" | \
sed "s|$4|\$INSTALL_DIR|" | \
sed '/ORIGIN/d'  | \
sed 's/\ $/\ \\/' | \
sed "s|^##|\\n# Compile executable|" | \
sed "s|^#$|#! /bin/bash\\nINSTALL_DIR=$4\\n\\n# Compile object|" >$2

chmod 755 $2
